### ISSUE TITLE
Can hcuppy used to identify principal diagnosis for DRG?

### ISSUE THREAD

**Issue by Raghu17s** [yubin-park/hcuppy#3]
Hi folks,

I am using drgpy to group multiple ICD's to single MSDRG. I am facing issue in identifying principal diagnosis from the given list of diagnosis ICD's. How can hcuppy be used to identify principal diagnosis which can help drgpy?

Thanks

**Comment by kevinbuchanjr** [comment]
Hi @Raghu17s,

This is not possible. Principal diagnoses should be designated on the claims files (i.e., in the data that is input to hcuppy). It is not possible for hcuppy to tease out which diagnosis code is principal because each claims processor indicates this differently (e.g., sometimes it is simply the first position in a claim line, while other times it appears in its own column). The short answer is that it should be identified in your input data, not as an output of hcuppy. Good luck!
